defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: "default"
  -
    scope:
      path: "index.md"
    values:
      nav_order: 1
  -
    scope:
      path: "new-project.md"
    values:
      nav_order: 2
  -
    scope:
      path: "existing-project.md"
    values:
      nav_order: 3
  -
    scope:
      path: "unity-guidelines.md"
    values:
      nav_order: 4
  -
    scope:
      path: "testen.md"
    values:
      nav_order: 5
  -
    scope:
      path: "functionalities.md"
    values:
      nav_order: 6
      has_children: true
  -
    scope:
      path: "exhibit-item-dashboard.md"
    values:
      parent: "functionalities.md"
      nav_order: 1