# Site settings
title: Project ARiO Docs
description: Step-by-step guide to setting up a development environment for new developers
url: "https://josvoogtio.github.io/TestRepo/"

# Theme settings
remote_theme: just-the-docs/just-the-docs

# Navigation structure
nav_order: 1
has_children: true

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "//github.com/weareyou.github.io/project-ario"

# Define navigation order for all pages
defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: "default"
  -
    scope:
      path: "index.md"
    values:
      nav_order: 1
  -
    scope:
      path: "new-project.md"
    values:
      nav_order: 2
  -
    scope:
      path: "existing-project.md"
    values:
      nav_order: 3
  -
    scope:
      path: "unity-guidelines.md"
    values:
      nav_order: 4
  -
    scope:
      path: "testen.md"
    values:
      nav_order: 5
  -
    scope:
      path: "functionalities.md"
    values:
      nav_order: 6
      has_children: true
  -
    scope:
      path: "exhibit-item-dashboard.md"
    values:
      parent: "functionalities.md"
      nav_order: 1
